user1 = User.create(name: 'Zack', password: 'blink182')

note1 = Note.create(title: 'Hail Caesar!', image: 'https://classroomclipart.com/images/gallery/Clipart/Ancient_Rome/TN_clipart-of-julius-caesar-ancient-roman-politican.jpg', description: "This is my first test note. I'm thrilled to be creating this note!! Yipee!!", category: 'scholarly', user_id: 1)
note2 = Note.create(title: 'Canal Smarts', image: 'https://us.123rf.com/450wm/anton345/anton3451811/anton345181100055/111434587-stock-vector-venice-beach-los-angeles-california-label-sign-logo-hand-drawn-lettering-modern-calligraphy-for-t-sh.jpg?ver=6', description: "This is my second test note. I'm thrilled to be creating this note!! Hooray!!", category: 'fun', user_id: 1)
note3 = Note.create(title: 'GhoOoOoOsts', image: 'https://www.pinclipart.com/picdir/middle/529-5298213_library-of-ghosts-jpg-royalty-free-png-files.png', description: "This is my third test note. I'm thrilled to be creating this note!! Cool!!", category: 'netfilx', user_id: 1)
note4 = Note.create(title: 'I wuv you!!', image: 'https://i.pinimg.com/originals/27/9a/66/279a667fa6f326a6ad3966efd1bc953d.png', description: "This is my catorce test note. I'm thrilled to be creating this note!! Bingo!!", category: 'fun', user_id: 1)
note5 = Note.create(title: "We're not alone", image: 'https://www.clker.com/cliparts/9/7/8/1/15163650521977078571galaxy-clipart-free.med.png', description: "This is my fifth test note. I'm thrilled to be creating this note!! Bingo!!", category: 'scholarly', user_id: 1)
note6 = Note.create(title: "Italian Food", image: 'https://i.pinimg.com/originals/21/e8/09/21e809c38a8cb6dfe3e5856500231b46.png', description: "This is my sixth test note. I'm thrilled to be creating this note!! Bingo!!", category: 'scholarly', user_id: 1)
note7 = Note.create(title: "Visit Macedonia", image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_map_of_North_Macedonia.svg/1200px-Flag_map_of_North_Macedonia.svg.png', description: "This is my seventh test note. I'm thrilled to be creating this note!! Bingo!!", category: 'scholarly', user_id: 1)
note8 = Note.create(title: "The fine line between crazy and genius", image: 'https://cdn.imgbin.com/10/20/24/imgbin-kanye-west-smiling-face-smiling-man-wearing-sunglasses-EFASbSVCtqsnfm8RsRFHwENWg.jpg', description: "This is my fifth test note. I'm thrilled to be creating this note!! Bingo!!", category: 'scholarly', user_id: 1)
note9 = Note.create(title: "Is 19 possible?", image: 'https://i.pinimg.com/originals/c0/7c/f3/c07cf3494c67fc9f8a5b1ac9539029d0.png', description: "This is my fifth test note. I'm thrilled to be creating this note!! Bingo!!", category: 'scholarly', user_id: 1)
note10 = Note.create(title: "'Maybe.'", image: 'https://media.boreme.com/post_thumbs/2014/Alan-Watts-The-story-of-the-Chinese-farmer.jpg', description: "This is my fifth test note. I'm thrilled to be creating this note!! Bingo!!", category: 'scholarly', user_id: 1)


